name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Permissions
        run: chmod +x ./scripts/update_version.sh

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          tag_format: ${version}
          branches: |
            ["master"]
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/github
            {
              "assets": ["src/__init__.py"]
            }
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
